In [43]:
#importing libraries
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

In [44]:
#loading our dataset.
df = pd.read_csv("movies_metadata.csv")
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [45]:
#shape of our data.
print(df.shape)

(45466, 24)

In [46]:
# checking for null values in the dataset.
print(df.isna().sum())

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

In [47]:
# checking for duplicate values
print(df.duplicated().sum())

13

In [48]:
# drop all duplicate rows.
df = df.drop_duplicates().reset_index(drop=True)

In [49]:
print(df.duplicated().sum())

0

In [50]:
# creating new dataframe with selected columns
df = df[['title','overview','genres','tagline','vote_average','popularity']]

In [51]:
df.head()

,title,overview,genres,tagline,vote_average,popularity
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",NaN,7.7,21.946943
1,Jumanji,When siblings Judy and Peter discover an encha...,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",Roll the dice and unleash the excitement!,6.9,17.015539
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...","[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",Friends are the people who let you be yourself...,6.1,3.859495
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,"[{'id': 35, 'name': 'Comedy'}]",Just When His World Is Back To Normal... He's ...,5.7,8.387519

In [52]:
print(df.isna().sum())

title               6
overview          954
genres              0
tagline         25045
vote_average        6
popularity          5
dtype: int64

In [53]:
# drop rows where title is null.
df = df.dropna(subset=['title'])

In [54]:
# filling with empty space.
df['overview'] = df['overview'].fillna('')

In [55]:
df.iloc[0]['genres']

"[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]"

In [56]:
import ast
# just only taking name from the df['genres'] dictionary.
df['genres'] = df['genres'].apply(lambda x : " ".join([i['name'] for i in ast.literal_eval(x)]))

In [57]:
df.head(5)

,title,overview,genres,tagline,vote_average,popularity
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,NaN,7.7,21.946943
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,6.9,17.015539
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,6.1,3.859495
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,5.7,8.387519

In [58]:
df['tagline'] = df['tagline'].fillna('')

In [59]:
# merging all these three columns into tags.
df['tags'] = df['overview']+" "+df['genres']+" "+df['tagline']

In [60]:
df.head(5)

,title,overview,genres,tagline,vote_average,popularity,tags
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,,7.7,21.946943,"Led by Woody, Andy's toys live happily in his ..."
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,6.9,17.015539,When siblings Judy and Peter discover an encha...
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129,A family wedding reignites the ancient feud be...
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,6.1,3.859495,"Cheated on, mistreated and stepped on, the wom..."
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,5.7,8.387519,Just when George Banks has recovered from his ...

In [61]:
df['tags'][1]

"When siblings Judy and Peter discover an enchanted board game that opens the door to a magical world, they unwittingly invite Alan -- an adult who's been trapped inside the game for 26 years -- into their living room. Alan's only hope for freedom is to finish the game, which proves risky as all three find themselves running from giant rhinoceroses, evil monkeys and other terrifying creatures. Adventure Fantasy Family Roll the dice and unleash the excitement!"

In [62]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

In [63]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [64]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

In [65]:
def preprocess_text(text):
    # converting to lowercase.
    text = str(text).lower()
    # next removing all the punctuation.
    text = re.sub(r'[^\w\s]', '', text)
    # next remove stop words.
    words = text.split()
    words = [word for word in words if word not in stop_words]
    # next lemmatizing the words.
    words = [lemmatizer.lemmatize(word) for word in words]
    return ' '.join(words)

In [66]:
df['tags'] = df['tags'].apply(preprocess_text)

In [67]:
df['tags'][1]

'sibling judy peter discover enchanted board game open door magical world unwittingly invite alan adult who trapped inside game 26 year living room alans hope freedom finish game prof risky three find running giant rhinoceros evil monkey terrifying creature adventure fantasy family roll dice unleash excitement'

In [68]:
df = df.reset_index(drop=True)

In [69]:
# using indices for each title. using pd.Series
indices = pd.Series(df.index, index=df['title']).drop_duplicates()
indices.head()

title
Toy Story                      0
Jumanji                        1
Grumpier Old Men               2
Waiting to Exhale              3
Father of the Bride Part II    4
dtype: int64

In [70]:
from sklearn.feature_extraction.text import TfidfVectorizer
# converting text to vectors
# using tf-idf vectorizer.
tfidf = TfidfVectorizer(max_features=50000,ngram_range=(1,2),stop_words='english')

In [71]:
# creating tfidf_matrix
tfidf_matrix = tfidf.fit_transform(df['tags'])

In [72]:
from sklearn.metrics.pairwise import cosine_similarity

In [73]:
#using cosine similarity to get similarity scores to understand which movies are similar
def recommend(title, n=10):
  if title not in indices:
    return ['Movie not found']

  idx = indices[title]
  sim_scores = cosine_similarity(tfidf_matrix[idx], tfidf_matrix).flatten()
  similar_idx = sim_scores.argsort()[::-1][1:n+1]
  return df['title'].iloc[similar_idx]

In [77]:
recommend('Avatar')

26547                                      Avatar 2
13883                          The Inhabited Island
26553                                Thor: Ragnarok
28633                          Stand by Me Doraemon
43431                        Moontrap: Target Earth
2457                                     The Matrix
6414     Lara Croft Tomb Raider: The Cradle of Life
21567                The Secret of the Third Planet
14119                          The Three Musketeers
9949                             A Trip to the Moon
Name: title, dtype: object

In [79]:
recommend('Waiting to Exhale')

21451            A Cry in the Night
31048             Da geht noch was!
30081    C'mon, Let's Live a Little
27325             Robin of Locksley
18497                 Woman in Love
16015                  Heartbreaker
18652          The Woman Who Drinks
22653                      Tentação
28233                    Kolmistaan
24516                 Madame Bovary
Name: title, dtype: object

In [80]:
recommend('The Godfather')

1178               The Godfather: Part II
44011    The Godfather Trilogy: 1972-1990
31957                    Honor Thy Father
23115                          Blood Ties
45391                               Aprel
18018                     A Cab for Three
28255     Judge Fayard Called the Sheriff
24166                              Cement
28264         Un milliard dans un billard
39252           Barrela: Escola de Crimes
Name: title, dtype: object